spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/##
spring.datasource.username=root
spring.datasource.password=###
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# these are connection details 
# that we usually store in the .env in the mern application 

# JWT config (base64 secret)
app.jwt.secret=##=
app.jwt.expiration-ms=86400000
